model: "bayes_net"
model_args:
  discretize_features: true
  bins: 5
  estimator: "mle"
  naive: true
  chunk_size: 200
  output_dir: "feature_output"
  visualization:
    enabled: true
    type: "network"
    output_file: "results/visualizations/bayes_net_structure.png"
    show: true

metrics: ["full"]