# model: "ann"
# batch_size: 32

# model_args:
#   epochs: 8

# metrics: ["accuracy_score", "auc_score", "f1_score"]

model: "bayes_net"
model_args:
  discretize_features: true
  bins: 5
  estimator: "mle"
  naive: true

metrics: ["accuracy_score"]